<a href="https://colab.research.google.com/github/erfanbyt/pytorch/blob/main/torch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notes

1. In general, it is better to not loop over the tensor, always there are some tensors operations, when you do the loop operations, you run the operation in over python, but using the tensor in-built operation will do it over GPU with use of C and Cuda and it is much faster.

2. 

In [ ]:
import torch

#### Tensors

In [ ]:
# number 
t1 = torch.tensor(4.)
print(t1, type(t1))

tensor(4.) <class 'torch.Tensor'>


In [ ]:
# vectors 
t2 = torch.tensor([1,2,3,4])
print(t2, type(t2))

tensor([1, 2, 3, 4]) <class 'torch.Tensor'>


In [ ]:
# matrix
t3 = torch.tensor([[1,2],
                  [3,4]])
print(t3)

tensor([[1, 2],
        [3, 4]])


In [ ]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([])
torch.Size([4])
torch.Size([2, 2])


#### Tensor operations and gradients

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)  # the second argument is only used for one the gradient is needed
b = torch.tensor(5., requires_grad=True)
print(x, y, b)

tensor(3.) tensor(17., grad_fn=<AddBackward0>) tensor(5., requires_grad=True)


In [ ]:
# arithmetic operations
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


Computing the derivatives 

In [ ]:
# it will compute the derivates for the variables with TRUE gradient condition
y.backward()

In [ ]:
print('dy/dx:', x.grad)  # cuz it was not chosen to get gradient by definition time
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


#### interoperability  with numpy

In [ ]:
import numpy as np

x = np.array([[1.,2], [3,4]])
print(x)

[[1. 2.]
 [3. 4.]]


In [ ]:
# converting the numpy array to a tensor -- using the numpy features --> uses the same memory locations
x_tensor = torch.from_numpy(x)
print(x_tensor, type(x_tensor))

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64) <class 'torch.Tensor'>


In [ ]:
# converting the numpy array to tensor -- using .tensor --> creates a new tensor in a new location 
x_tensor_2 = torch.tensor(x)
print(x_tensor_2)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
# converting the tensor back to numpy 
x = x_tensor.numpy()
print(x, type(x))

[[1. 2.]
 [3. 4.]] <class 'numpy.ndarray'>
